[2024-09-01T16:16:00.782+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-01T16:16:00.812+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_airbnb_etl.read_raw_data manual__2024-09-01T16:15:52+00:00 [queued]>
[2024-09-01T16:16:00.830+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_airbnb_etl.read_raw_data manual__2024-09-01T16:15:52+00:00 [queued]>
[2024-09-01T16:16:00.831+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-01T16:16:00.860+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): read_raw_data> on 2024-09-01 16:15:52+00:00
[2024-09-01T16:16:00.872+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=969) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T16:16:00.875+0000] {standard_task_runner.py:72} INFO - Started process 971 to run task
[2024-09-01T16:16:00.876+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_airbnb_etl', 'read_raw_data', 'manual__2024-09-01T16:15:52+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/nyc_airbnb_etl.py', '--cfg-path', '/tmp/tmp8ktlb_90']
[2024-09-01T16:16:00.878+0000] {standard_task_runner.py:105} INFO - Job 242: Subtask read_raw_data
[2024-09-01T16:16:00.964+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_airbnb_etl.read_raw_data manual__2024-09-01T16:15:52+00:00 [running]> on host b74353bc56c3
[2024-09-01T16:16:01.245+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_airbnb_etl' AIRFLOW_CTX_TASK_ID='read_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T16:15:52+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T16:15:52+00:00'
[2024-09-01T16:16:01.253+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-01T16:16:01.258+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-01T16:16:01.263+0000] {logging_mixin.py:190} INFO - Current task name:read_raw_data state:running start_date:2024-09-01 16:16:00.814138+00:00
[2024-09-01T16:16:01.264+0000] {logging_mixin.py:190} INFO - Dag name:nyc_airbnb_etl and current dag run status:running
[2024-09-01T16:16:01.266+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-01T16:16:01.268+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nyc_airbnb_etl.py", line 34, in read_raw_data
    raise FileNotFoundError(f"File does not exist: {path}")
FileNotFoundError: File does not exist: /opt/***/aw/AB_NYC_2019.csv
[2024-09-01T16:16:01.297+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-01T16:16:01.298+0000] {logging_mixin.py:190} INFO - Task start:2024-09-01 16:16:00.814138+00:00 end:2024-09-01 16:16:01.296836+00:00 duration:0.482698
[2024-09-01T16:16:01.299+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): read_raw_data> dag:<DAG: nyc_airbnb_etl> dagrun:<DagRun nyc_airbnb_etl @ 2024-09-01 16:15:52+00:00: manual__2024-09-01T16:15:52+00:00, state:running, queued_at: 2024-09-01 16:15:56.976502+00:00. externally triggered: True>
[2024-09-01T16:16:01.300+0000] {logging_mixin.py:190} INFO - Failure caused by File does not exist: /opt/***/aw/AB_NYC_2019.csv
[2024-09-01T16:16:01.301+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=nyc_airbnb_etl, task_id=read_raw_data, run_id=manual__2024-09-01T16:15:52+00:00, execution_date=20240901T161552, start_date=20240901T161600, end_date=20240901T161601
[2024-09-01T16:16:01.322+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-01T16:16:01.323+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 242 for task read_raw_data (File does not exist: /opt/***/aw/AB_NYC_2019.csv; 971)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nyc_airbnb_etl.py", line 34, in read_raw_data
    raise FileNotFoundError(f"File does not exist: {path}")
FileNotFoundError: File does not exist: /opt/***/aw/AB_NYC_2019.csv
[2024-09-01T16:16:01.377+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-01T16:16:01.398+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-09-01T16:16:01.429+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T16:16:01.437+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
