[2024-09-01T16:31:42.684+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-01T16:31:42.714+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_airbnb_etl.read_raw_data manual__2024-09-01T16:31:35+00:00 [queued]>
[2024-09-01T16:31:42.728+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_airbnb_etl.read_raw_data manual__2024-09-01T16:31:35+00:00 [queued]>
[2024-09-01T16:31:42.730+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-01T16:31:42.756+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): read_raw_data> on 2024-09-01 16:31:35+00:00
[2024-09-01T16:31:42.770+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1178) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T16:31:42.773+0000] {standard_task_runner.py:72} INFO - Started process 1180 to run task
[2024-09-01T16:31:42.773+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_airbnb_etl', 'read_raw_data', 'manual__2024-09-01T16:31:35+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/nyc_airbnb_etl.py', '--cfg-path', '/tmp/tmp909v6ion']
[2024-09-01T16:31:42.775+0000] {standard_task_runner.py:105} INFO - Job 248: Subtask read_raw_data
[2024-09-01T16:31:42.866+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_airbnb_etl.read_raw_data manual__2024-09-01T16:31:35+00:00 [running]> on host b74353bc56c3
[2024-09-01T16:31:43.041+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_airbnb_etl' AIRFLOW_CTX_TASK_ID='read_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T16:31:35+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T16:31:35+00:00'
[2024-09-01T16:31:43.044+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-01T16:31:43.045+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-01T16:31:43.046+0000] {logging_mixin.py:190} INFO - Current task name:read_raw_data state:running start_date:2024-09-01 16:31:42.715422+00:00
[2024-09-01T16:31:43.047+0000] {logging_mixin.py:190} INFO - Dag name:nyc_airbnb_etl and current dag run status:running
[2024-09-01T16:31:43.048+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-01T16:31:43.050+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nyc_airbnb_etl.py", line 34, in read_raw_data
    raise FileNotFoundError(f"File does not exist: {path}")
FileNotFoundError: File does not exist: /opt/***/rw/AB_NYC_2019.csv
[2024-09-01T16:31:43.074+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-01T16:31:43.076+0000] {logging_mixin.py:190} INFO - Task start:2024-09-01 16:31:42.715422+00:00 end:2024-09-01 16:31:43.073651+00:00 duration:0.358229
[2024-09-01T16:31:43.077+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): read_raw_data> dag:<DAG: nyc_airbnb_etl> dagrun:<DagRun nyc_airbnb_etl @ 2024-09-01 16:31:35+00:00: manual__2024-09-01T16:31:35+00:00, state:running, queued_at: 2024-09-01 16:31:39.033352+00:00. externally triggered: True>
[2024-09-01T16:31:43.078+0000] {logging_mixin.py:190} INFO - Failure caused by File does not exist: /opt/***/rw/AB_NYC_2019.csv
[2024-09-01T16:31:43.079+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=nyc_airbnb_etl, task_id=read_raw_data, run_id=manual__2024-09-01T16:31:35+00:00, execution_date=20240901T163135, start_date=20240901T163142, end_date=20240901T163143
[2024-09-01T16:31:43.101+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-01T16:31:43.102+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 248 for task read_raw_data (File does not exist: /opt/***/rw/AB_NYC_2019.csv; 1180)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nyc_airbnb_etl.py", line 34, in read_raw_data
    raise FileNotFoundError(f"File does not exist: {path}")
FileNotFoundError: File does not exist: /opt/***/rw/AB_NYC_2019.csv
[2024-09-01T16:31:43.152+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-01T16:31:43.172+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-09-01T16:31:43.199+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T16:31:43.209+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
